services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: f1db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 


  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app 
    depends_on:
      - db 

volumes:
  pgdata: